import type React from "react";
import type { SvgProps } from "react-native-svg";

import {
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalOutline,
  ArrowPathIcon as ArrowPathOutline,
  ArrowTrendingUpIcon as ArrowTrendingUpOutline,
  Bars3Icon as Bars3Outline,
  BeakerIcon as BeakerOutline,
  BoltIcon as BoltOutline,
  CalendarDaysIcon as CalendarDaysOutline,
  CameraIcon as CameraOutline,
  ChartBarIcon as ChartBarOutline,
  CheckCircleIcon as CheckCircleOutline,
  CheckIcon as CheckOutline,
  ChevronDownIcon as ChevronDownOutline,
  ChevronLeftIcon as ChevronLeftOutline,
  ChevronRightIcon as ChevronRightOutline,
  ChevronUpIcon as ChevronUpOutline,
  ClockIcon as ClockOutline,
  Cog6ToothIcon as Cog6ToothOutline,
  EllipsisVerticalIcon as EllipsisVerticalOutline,
  FireIcon as FireOutline,
  FunnelIcon as FunnelOutline,
  HeartIcon as HeartOutline,
  HomeIcon as HomeOutline,
  MagnifyingGlassIcon as MagnifyingGlassOutline,
  PencilSquareIcon as PencilSquareOutline,
  PlayIcon as PlayOutline,
  PlusCircleIcon as PlusCircleOutline,
  PlusIcon as PlusOutline,
  StarIcon as StarOutline,
  StopIcon as StopOutline,
  TrashIcon as TrashOutline,
  TrophyIcon as TrophyOutline,
  UserCircleIcon as UserCircleOutline,
  XMarkIcon as XMarkOutline,
} from "react-native-heroicons/outline";
import {
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalSolid,
  ArrowPathIcon as ArrowPathSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpSolid,
  Bars3Icon as Bars3Solid,
  BeakerIcon as BeakerSolid,
  BoltIcon as BoltSolid,
  CalendarDaysIcon as CalendarDaysSolid,
  CameraIcon as CameraSolid,
  ChartBarIcon as ChartBarSolid,
  CheckCircleIcon as CheckCircleSolid,
  CheckIcon as CheckSolid,
  ChevronDownIcon as ChevronDownSolid,
  ChevronLeftIcon as ChevronLeftSolid,
  ChevronRightIcon as ChevronRightSolid,
  ChevronUpIcon as ChevronUpSolid,
  ClockIcon as ClockSolid,
  Cog6ToothIcon as Cog6ToothSolid,
  EllipsisVerticalIcon as EllipsisVerticalSolid,
  FireIcon as FireSolid,
  FunnelIcon as FunnelSolid,
  HeartIcon as HeartSolid,
  HomeIcon as HomeSolid,
  MagnifyingGlassIcon as MagnifyingGlassSolid,
  PencilSquareIcon as PencilSquareSolid,
  PlayIcon as PlaySolid,
  PlusCircleIcon as PlusCircleSolid,
  PlusIcon as PlusSolid,
  StarIcon as StarSolid,
  StopIcon as StopSolid,
  TrashIcon as TrashSolid,
  TrophyIcon as TrophySolid,
  UserCircleIcon as UserCircleSolid,
  XMarkIcon as XMarkSolid,
} from "react-native-heroicons/solid";

/** Heroicon component shape used across the app bridge. */
export type HeroIconComponent = React.FC<{
  color?: string;
  size?: number;
  strokeWidth?: number;
} & Pick<SvgProps, "accessibilityLabel">>;

export {
  AdjustmentsHorizontalOutline,
  AdjustmentsHorizontalSolid,
  ArrowPathOutline,
  ArrowPathSolid,
  ArrowTrendingUpOutline,
  ArrowTrendingUpSolid,
  Bars3Outline,
  Bars3Solid,
  BeakerOutline,
  BeakerSolid,
  BoltOutline,
  BoltSolid,
  CalendarDaysOutline,
  CalendarDaysSolid,
  CameraOutline,
  CameraSolid,
  ChartBarOutline,
  ChartBarSolid,
  CheckCircleOutline,
  CheckCircleSolid,
  CheckOutline,
  CheckSolid,
  ChevronDownOutline,
  ChevronDownSolid,
  ChevronLeftOutline,
  ChevronLeftSolid,
  ChevronRightOutline,
  ChevronRightSolid,
  ChevronUpOutline,
  ChevronUpSolid,
  ClockOutline,
  ClockSolid,
  Cog6ToothOutline,
  Cog6ToothSolid,
  EllipsisVerticalOutline,
  EllipsisVerticalSolid,
  FireOutline,
  FireSolid,
  FunnelOutline,
  FunnelSolid,
  HeartOutline,
  HeartSolid,
  HomeOutline,
  HomeSolid,
  MagnifyingGlassOutline,
  MagnifyingGlassSolid,
  PencilSquareOutline,
  PencilSquareSolid,
  PlayOutline,
  PlaySolid,
  PlusCircleOutline,
  PlusCircleSolid,
  PlusOutline,
  PlusSolid,
  StarOutline,
  StarSolid,
  StopOutline,
  StopSolid,
  TrashOutline,
  TrashSolid,
  TrophyOutline,
  TrophySolid,
  UserCircleOutline,
  UserCircleSolid,
  XMarkOutline,
  XMarkSolid,
};
