import { config } from "dotenv";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

config({ path: resolve(__dirname, "../../../../.env") });

import { createHevyClient } from "./hevy-api-client";
import {
  HEVY_EQUIPMENT,
  HEVY_EXERCISE_TYPES,
  HEVY_MUSCLE_GROUPS,
  HEVY_TO_PRISMA_MAP,
  hevySlugToName,
} from "./mappings";
import type { HevyExerciseTemplate } from "./types";

function analyzeObject(obj: Record<string, unknown>, prefix = ""): string[] {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (value === null) {
      lines.push(`- \`${path}\`: null`);
    } else if (Array.isArray(value)) {
      const sample = value[0];
      const inner =
        sample && typeof sample === "object"
          ? `object { ${Object.keys(sample as object).join(", ")} }`
          : typeof sample;
      lines.push(`- \`${path}\`: array<${inner ?? "unknown"}> (length ${value.length})`);
    } else {
      lines.push(`- \`${path}\`: ${typeof value}${typeof value === "string" ? ` e.g. "${value.slice(0, 40)}"` : ""}`);
    }
  }
  return lines;
}

async function main() {
  const client = createHevyClient();
  const templates = await client.paginate<HevyExerciseTemplate>(
    "/v1/exercise_templates",
    "exercise_templates",
    100,
    1,
  );

  const sample = templates[0];
  if (!sample) throw new Error("No templates to analyze");

  const md = `# Hevy API → Kak Fit Schema Mapping

> Auto-generated by \`analyze-hevy-schema.ts\`. Hevy public API v0.0.1.
> Docs: https://api.hevyapp.com/docs/

## Important: What Hevy actually provides

The Hevy **public REST API** does **not** have separate endpoints for:
- \`/exercises\`, \`/muscles\`, \`/equipment\`, \`/categories\`
- \`/images\`, \`/media\`, exercise instructions, or videos

Exercise catalog data comes from **\`GET /v1/exercise_templates\`** only.

### Live sample exercise template fields

${analyzeObject(sample as unknown as Record<string, unknown>).join("\n")}

## Endpoint inventory

| Endpoint | Purpose |
|----------|---------|
| \`GET /v1/user/info\` | Authenticated user profile |
| \`GET /v1/exercise_templates\` | Exercise catalog (paginated, max 100/page) |
| \`GET /v1/exercise_templates/{id}\` | Single exercise template |
| \`POST /v1/exercise_templates\` | Create custom exercise |
| \`GET /v1/workouts\` | Workout history |
| \`GET /v1/routines\` | Saved routines |
| \`GET /v1/routine_folders\` | Routine folders |
| \`GET /v1/exercise_history/{id}\` | Per-exercise set history |
| \`GET /v1/body_measurements\` | Body measurements |

## Field mapping: Hevy → Prisma

| Hevy field | Kak Fit field | Notes |
|------------|---------------|-------|
| \`exercise_templates.id\` | \`Exercise.hevyId\` | String ID e.g. \`3BC06AD3\` |
| \`exercise_templates.title\` | \`Exercise.name\` | |
| \`exercise_templates.type\` | \`Category.name\` | Mapped via exercise type slug |
| \`exercise_templates.primary_muscle_group\` | \`ExerciseMuscle\` | \`isPrimary: true\` |
| \`exercise_templates.secondary_muscle_groups[]\` | \`ExerciseMuscle\` | \`isPrimary: false\` |
| \`exercise_templates.equipment\` | \`ExerciseEquipment\` | Equipment enum slug |
| \`exercise_templates.is_custom\` | — | Skip \`true\` for global catalog import |
| _(not provided)_ | \`Exercise.instructions\` | Use Wger or manual entry |
| _(not provided)_ | \`Exercise.imageUrl\` | Use Wger import |
| _(not provided)_ | \`Exercise.videoUrl\` | Not available from Hevy API |

## Reference enums (not separate API resources)

### Muscles (${HEVY_MUSCLE_GROUPS.length})

${HEVY_MUSCLE_GROUPS.map((s) => `- \`${s}\` → ${hevySlugToName(s)}`).join("\n")}

### Equipment (${HEVY_EQUIPMENT.length})

${HEVY_EQUIPMENT.map((s) => `- \`${s}\` → ${hevySlugToName(s)}`).join("\n")}

### Exercise types / categories (${HEVY_EXERCISE_TYPES.length})

${HEVY_EXERCISE_TYPES.map((s) => `- \`${s}\` → ${hevySlugToName(s)}`).join("\n")}

## Prisma mapping object

\`\`\`json
${JSON.stringify(HEVY_TO_PRISMA_MAP, null, 2)}
\`\`\`

## Schema gaps (Hevy does NOT provide — optional future fields)

These were requested in the import plan but are **not in Hevy's API response**:

- Difficulty level (beginner/intermediate/advanced)
- Force type (push/pull/static)
- Mechanic (compound/isolation)
- Multiple image URLs / video URLs
- Alternative names / tags / popularity score

**Recommendation:** Keep using Wger (\`pnpm db:import\`) for images and instructions. Use Hevy import for exercise **names**, **muscle/equipment taxonomy**, and **type** alignment.

## TypeScript types

See \`packages/db/scripts/hevy/types.ts\`:
- \`HevyExerciseTemplate\`
- \`HevyMuscle\`, \`HevyEquipment\`, \`HevyCategory\` (derived from enums)
- \`HevyExerciseImage\`, \`HevyExerciseVideo\`, \`HevyExerciseInstruction\` (stubs — API has no data)
`;

  const outPath = resolve(__dirname, "../../../../docs/HEVY_API_MAPPING.md");
  await writeFile(outPath, md, "utf8");
  console.log(`Wrote ${outPath}`);
  console.log(`Analyzed ${templates.length} sample templates from page 1.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
