#!/usr/bin/env bash
# Sync env across apps: LAN IP, Supabase DATABASE_URL, copy to web + mobile
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — copy from .env.example"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

IP=$(hostname -I | awk '{print $1}')
CURRENT_API="${EXPO_PUBLIC_API_URL:-}"
USE_LAN_API=true
if [[ "$CURRENT_API" == https://* ]]; then
  USE_LAN_API=false
fi

if [[ -n "$IP" && "$USE_LAN_API" == true ]]; then
  if grep -q '^EXPO_PUBLIC_API_URL=' "$ENV_FILE"; then
    sed -i "s|^EXPO_PUBLIC_API_URL=.*|EXPO_PUBLIC_API_URL=\"http://${IP}:3000\"|" "$ENV_FILE"
  else
    echo "EXPO_PUBLIC_API_URL=\"http://${IP}:3000\"" >> "$ENV_FILE"
  fi

  if grep -q '^BETTER_AUTH_URL=' "$ENV_FILE"; then
    sed -i "s|^BETTER_AUTH_URL=.*|BETTER_AUTH_URL=\"http://${IP}:3000\"|" "$ENV_FILE"
  else
    echo "BETTER_AUTH_URL=\"http://${IP}:3000\"" >> "$ENV_FILE"
  fi
elif [[ "$USE_LAN_API" == false ]]; then
  echo "Keeping deployed API URL: $CURRENT_API"
fi

# Supabase Postgres — Prisma pattern (Dashboard → Connect → ORMs → Prisma)
SUPABASE_REF="${SUPABASE_PROJECT_REF:-}"
POOLER_HOST="${SUPABASE_POOLER_HOST:-}"
if [[ -n "${SUPABASE_DB_PASSWORD:-}" && -n "$SUPABASE_REF" && -n "$POOLER_HOST" ]]; then
  # Session pooler (:5432) for direct/migration connections and long-lived servers.
  DIRECT_URL_VAL="postgresql://postgres.${SUPABASE_REF}:${SUPABASE_DB_PASSWORD}@${POOLER_HOST}:5432/postgres?schema=public&sslmode=require"

  ACCELERATE_URL="${PRISMA_ACCELERATE_URL:-}"
  CURRENT_DB=$(grep -E '^DATABASE_URL=' "$ENV_FILE" | head -1 || true)
  USE_ACCELERATE=false
  if [[ -n "$ACCELERATE_URL" ]]; then
    USE_ACCELERATE=true
  elif [[ "$CURRENT_DB" == *"prisma://"* || "$CURRENT_DB" == *"prisma+postgres://"* || "$CURRENT_DB" == *"accelerate.prisma-data.net"* ]]; then
    USE_ACCELERATE=true
  fi

  if [[ "$USE_ACCELERATE" == true ]]; then
    python3 - "$ENV_FILE" "$DIRECT_URL_VAL" "$ACCELERATE_URL" <<'PY'
import pathlib, re, sys
path, direct_url, accelerate_url = sys.argv[1], sys.argv[2], sys.argv[3]
lines = pathlib.Path(path).read_text().splitlines()
out = []
updates = {"DIRECT_URL": direct_url}
if accelerate_url:
    updates["DATABASE_URL"] = accelerate_url
seen = set()
for line in lines:
    m = re.match(r"^([A-Z_][A-Z0-9_]*)=", line)
    if m and m.group(1) in updates:
        key = m.group(1)
        out.append(f'{key}="{updates[key]}"')
        seen.add(key)
    else:
        out.append(line)
for key, val in updates.items():
    if key not in seen:
        out.append(f'{key}="{val}"')
pathlib.Path(path).write_text("\n".join(out) + "\n")
PY
    if [[ -n "$ACCELERATE_URL" ]]; then
      echo "Set DATABASE_URL from PRISMA_ACCELERATE_URL + updated DIRECT_URL"
    else
      echo "Updated DIRECT_URL only (keeping Prisma Accelerate DATABASE_URL)"
    fi
  else
    DB_URL="postgresql://postgres.${SUPABASE_REF}:${SUPABASE_DB_PASSWORD}@${POOLER_HOST}:5432/postgres?schema=public&sslmode=require&connection_limit=5"
    python3 - "$ENV_FILE" "$DB_URL" "$DIRECT_URL_VAL" <<'PY'
import pathlib, re, sys
path, db_url, direct_url = sys.argv[1], sys.argv[2], sys.argv[3]
updates = {"DATABASE_URL": db_url, "DIRECT_URL": direct_url}
lines = pathlib.Path(path).read_text().splitlines()
out, seen = [], set()
for line in lines:
    m = re.match(r"^([A-Z_][A-Z0-9_]*)=", line)
    if m and m.group(1) in updates:
        key = m.group(1)
        out.append(f'{key}="{updates[key]}"')
        seen.add(key)
    else:
        out.append(line)
for key, val in updates.items():
    if key not in seen:
        out.append(f'{key}="{val}"')
pathlib.Path(path).write_text("\n".join(out) + "\n")
PY
    echo "Using Supabase pooler → ${POOLER_HOST}"
  fi
fi

cp "$ENV_FILE" "$ROOT/apps/web/.env.local"

# Mobile only needs public Expo vars (not DB secrets)
{
  echo "# Auto-generated by scripts/sync-ip.sh — do not commit"
  grep '^EXPO_PUBLIC_' "$ENV_FILE" || true
} > "$ROOT/apps/mobile/.env"

echo "Synced env files"
[[ -n "$IP" ]] && echo "  LAN IP: $IP"
echo "  API: ${EXPO_PUBLIC_API_URL:-http://localhost:3000}"
[[ -n "${USDA_API_KEY:-}" ]] && echo "  USDA_API_KEY: set" || echo "  ⚠ USDA_API_KEY: missing"
[[ -n "${SUPABASE_DB_PASSWORD:-}" ]] && echo "  Database: Supabase (${SUPABASE_POOLER_HOST:-pooler})" || echo "  Database: ${DATABASE_URL:-local}"
