#!/usr/bin/env bash
# Sync env across apps: LAN IP, Supabase DATABASE_URL, copy to web + mobile
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — copy from .env.example"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

IP=$(hostname -I | awk '{print $1}')
if [[ -n "$IP" ]]; then
  if grep -q '^EXPO_PUBLIC_API_URL=' "$ENV_FILE"; then
    sed -i "s|^EXPO_PUBLIC_API_URL=.*|EXPO_PUBLIC_API_URL=\"http://${IP}:3000\"|" "$ENV_FILE"
  else
    echo "EXPO_PUBLIC_API_URL=\"http://${IP}:3000\"" >> "$ENV_FILE"
  fi

  if grep -q '^BETTER_AUTH_URL=' "$ENV_FILE"; then
    sed -i "s|^BETTER_AUTH_URL=.*|BETTER_AUTH_URL=\"http://${IP}:3000\"|" "$ENV_FILE"
  else
    echo "BETTER_AUTH_URL=\"http://${IP}:3000\"" >> "$ENV_FILE"
  fi
fi

# Supabase Postgres — Prisma pattern (Dashboard → Connect → ORMs → Prisma)
SUPABASE_REF="${SUPABASE_PROJECT_REF:-}"
POOLER_HOST="${SUPABASE_POOLER_HOST:-}"
if [[ -n "${SUPABASE_DB_PASSWORD:-}" && -n "$SUPABASE_REF" && -n "$POOLER_HOST" ]]; then
  # Use the SESSION pooler (:5432) for the runtime connection. This app runs as a
  # long-lived Node server (not serverless), so a persistent connection that
  # reuses prepared statements is 3-5x faster than the transaction pooler (:6543).
  DB_URL="postgresql://postgres.${SUPABASE_REF}:${SUPABASE_DB_PASSWORD}@${POOLER_HOST}:5432/postgres?schema=public&sslmode=require&connection_limit=5"
  DIRECT_URL_VAL="postgresql://postgres.${SUPABASE_REF}:${SUPABASE_DB_PASSWORD}@${POOLER_HOST}:5432/postgres?schema=public&sslmode=require"

  python3 - "$ENV_FILE" "$DB_URL" "$DIRECT_URL_VAL" <<'PY'
import pathlib, re, sys
path, db_url, direct_url = sys.argv[1], sys.argv[2], sys.argv[3]
updates = {"DATABASE_URL": db_url, "DIRECT_URL": direct_url}
lines = pathlib.Path(path).read_text().splitlines()
out, seen = [], set()
for line in lines:
    m = re.match(r"^([A-Z_][A-Z0-9_]*)=", line)
    if m and m.group(1) in updates:
        key = m.group(1)
        out.append(f'{key}="{updates[key]}"')
        seen.add(key)
    else:
        out.append(line)
for key, val in updates.items():
    if key not in seen:
        out.append(f'{key}="{val}"')
pathlib.Path(path).write_text("\n".join(out) + "\n")
PY
  echo "Using Supabase pooler → ${POOLER_HOST}"
fi

cp "$ENV_FILE" "$ROOT/apps/web/.env.local"

# Mobile only needs public Expo vars (not DB secrets)
{
  echo "# Auto-generated by scripts/sync-ip.sh — do not commit"
  grep '^EXPO_PUBLIC_' "$ENV_FILE" || true
} > "$ROOT/apps/mobile/.env"

echo "Synced env files"
[[ -n "$IP" ]] && echo "  LAN IP: $IP"
echo "  API: ${EXPO_PUBLIC_API_URL:-http://localhost:3000}"
[[ -n "${USDA_API_KEY:-}" ]] && echo "  USDA_API_KEY: set" || echo "  ⚠ USDA_API_KEY: missing"
[[ -n "${SUPABASE_DB_PASSWORD:-}" ]] && echo "  Database: Supabase (${SUPABASE_POOLER_HOST:-pooler})" || echo "  Database: ${DATABASE_URL:-local}"
